import {test,expect,type Page} from '@playwright/test';
const qa=(p:Page,fn:string)=>p.evaluate(fn);
async function create(p:Page){await p.goto('/?qa=1');await p.locator('[data-nav="deploy"]').first().click();await p.locator('[data-create-run]').click();if(await p.locator('[data-skip-lessons]').isVisible())await p.locator('[data-skip-lessons]').click();await expect(p.locator('#arena canvas')).toBeVisible();}
async function buyDeploy(p:Page){await p.evaluate(()=>{const q=(window as any).__variantQA;q.repo.transaction((d:any)=>{d.active.shop[0]='V-001'});q.render();});await p.locator('[data-buy="0"]').click();await p.locator('[data-unit]').first().click();await p.locator('[data-cell="27"]').click();}
test('brand, five primal founders, 45 hidden archive nodes and accessible network',async({page})=>{await page.goto('/?qa=1');await expect(page).toHaveTitle('VARIANT ZERO｜零号变种');await page.locator('.sidebar [data-nav="archive"]').click();await expect(page.locator('[data-node]')).toHaveCount(45);await expect(page.locator('.network-node.discovered')).toHaveCount(5);await page.locator('[data-node="V-006"]').focus();await page.keyboard.press('Enter');await expect(page.locator('#archive-detail')).toContainText('未解析');await page.locator('[data-archive-mode="list"]').click();await expect(page.locator('.species-card')).toHaveCount(45);await expect(page.locator('.unknown')).not.toHaveCount(0);});
for(const [width,height]of [[1280,720],[1366,768],[1440,900]])test(`deploy shop full layout ${width}`,async({page})=>{const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width,height});await create(page);await buyDeploy(page);const bounds=await page.locator('#shop').boundingBox();expect(bounds!.y+bounds!.height).toBeLessThanOrEqual(height+1);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(width);const board=await page.locator('.arena-wrap').boundingBox();expect(board!.width).toBeGreaterThanOrEqual(500);expect(board!.height).toBeGreaterThanOrEqual(375);await page.screenshot({animations:'disabled',path:`.verification/variant/deploy-${width}.png`});expect(errors).toEqual([]);});
test('prepare mutations persist, battle reload same round, loss rewards once',async({page})=>{await create(page);await buyDeploy(page);const before=await page.evaluate(()=>structuredClone((window as any).__variantQA.repo.data.active));await page.locator('[data-start]').click();await page.reload();await expect(page.locator('[data-nav="deploy"]').first()).toBeVisible();await page.locator('[data-nav="deploy"]').first().click();await expect(page.locator('[data-start]')).toBeEnabled();const after=await page.evaluate(()=>(window as any).__variantQA.repo.data.active);expect(after.units).toEqual(before.units);expect(after.shop).toEqual(before.shop);await page.locator('[data-start]').click();await page.evaluate(()=>{const q=(window as any).__variantQA;const b=q.combat;b.status='running';while(b.status==='running'){b.update(.25);b.drainEvents();}q.finishBattle();});await expect(page.locator('[data-next]')).toBeVisible();const reward=await page.evaluate(()=>JSON.stringify((window as any).__variantQA.repo.data.research.reagents));await page.evaluate(()=>(window as any).__variantQA.finishBattle());expect(await page.evaluate(()=>JSON.stringify((window as any).__variantQA.repo.data.research.reagents))).toBe(reward);await page.locator('[data-next]').click();await expect(page.locator('#command h1')).toContainText('2');});
test('experiment cancel preserves resources, confirmed result persists and settings focus',async({page})=>{await page.goto('/?qa=1');await page.locator('[data-nav="lab"]').first().click();if(await page.locator('[data-skip-lessons]').isVisible())await page.locator('[data-skip-lessons]').click();const before=await page.evaluate(()=>JSON.stringify((window as any).__variantQA.repo.data.research));await page.locator('[data-experiment]').click();await page.keyboard.press('Escape');expect(await page.evaluate(()=>JSON.stringify((window as any).__variantQA.repo.data.research))).toBe(before);await page.locator('[data-experiment]').click();await page.locator('[data-confirm-experiment]').click();await expect(page.locator('[role="dialog"]')).toContainText('实验完成');await page.keyboard.press('Escape');await page.reload();expect(await page.evaluate(()=>(window as any).__variantQA.repo.data.research.experiments)).toBe(1);await page.locator('[data-settings]').click();await page.locator('[data-volume="musicVolume"]').fill('36');await page.locator('#reduced').check();await page.locator('.modal-actions [data-close]').focus();await page.keyboard.press('Tab');await expect(page.locator('.modal-head [data-close]')).toBeFocused();await page.keyboard.press('Shift+Tab');await expect(page.locator('.modal-actions [data-close]')).toBeFocused();await page.keyboard.press('Escape');await expect(page.locator('[data-settings]')).toBeFocused();await page.reload();expect(await page.evaluate(()=>(window as any).__variantQA.repo.data.settings.musicVolume)).toBe(.36);});
test('abandon confirmation cancels without state mutation and blur requires active continue',async({page})=>{await create(page);await buyDeploy(page);await page.locator('[data-start]').click();await page.locator('[data-abandon]').click();expect(await page.evaluate(()=>(window as any).__variantQA.combat.status)).toBe('paused');await page.keyboard.press('Escape');expect(await page.evaluate(()=>(window as any).__variantQA.combat.status)).toBe('running');await page.evaluate(()=>window.dispatchEvent(new Event('blur')));await expect(page.locator('[data-pause]')).toHaveText('主动继续');expect(await page.evaluate(()=>(window as any).__variantQA.audio.debug().activeSfx)).toBe(0);await page.locator('[data-pause]').click();expect(await page.evaluate(()=>(window as any).__variantQA.combat.status)).toBe('running');});
test('mobile terminal pages no horizontal overflow',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto('/?qa=1');for(const name of ['hub','archive','lab','records','deploy']){await page.locator('[data-menu]').click();await page.locator(`.sidebar [data-nav="${name}"]`).first().click();expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(390);}await page.screenshot({animations:'disabled',path:'.verification/variant/mobile-pool.png',fullPage:true});});
for(const [width,height] of [[1280,720],[1366,768],[1440,900]])test(`immersive home stays in viewport ${width}`,async({page})=>{await page.setViewportSize({width,height});await page.goto('/?qa=1');await page.waitForTimeout(400);expect(await page.evaluate(()=>document.documentElement.scrollHeight)).toBeLessThanOrEqual(height);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(width);await expect(page.locator('.resident')).toHaveCount(1);await expect(page.locator('.sidebar [data-nav="deploy"]')).toBeVisible();await page.locator('[data-home-family="fungi"]').click();await expect(page.locator('.home-growth')).toContainText('原孢体');await expect(page.locator('.home-growth .unknown')).toHaveCount(2);await page.screenshot({animations:'disabled',path:`.verification/immersive/home-${width}.png`});});
test('mobile drawer keyboard focus and page navigation',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto('/?qa=1');await page.locator('[data-menu]').click();await expect(page.locator('[data-dismiss-menu].drawer-close')).toBeFocused();await page.keyboard.press('Shift+Tab');await expect(page.locator('.sidebar [data-settings]')).toBeFocused();await page.keyboard.press('Escape');await expect(page.locator('[data-menu]')).toBeFocused();await page.locator('[data-menu]').click();await page.locator('.sidebar [data-nav="archive"]').click();await expect(page.locator('.sidebar')).not.toBeVisible();await expect(page.locator('#network-viewport')).toBeVisible();await page.locator('[data-node="V-006"]').focus();await page.keyboard.press('Enter');await expect(page.locator('#archive-detail')).toContainText('未解析');expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(390);await page.screenshot({animations:'disabled',path:'.verification/immersive/archive-mobile.png',fullPage:true});});
test('return home preserves battle, continue stays paused, reduced motion',async({page})=>{await create(page);await buyDeploy(page);await page.locator('[data-start]').click();await page.locator('#command [data-nav="hub"]').click();expect(await page.evaluate(()=>(window as any).__variantQA.combat.status)).toBe('paused');await expect(page.locator('.base-status')).toContainText('回合 1');await page.locator('.sidebar [data-nav="deploy"]').click();await expect(page.locator('[data-pause]')).toContainText('主动继续');await page.locator('[data-settings]').last().click();await page.locator('#reduced').check();await page.keyboard.press('Escape');await page.locator('#command [data-nav="hub"]').click();expect(await page.locator('.resident').first().evaluate(e=>getComputedStyle(e).animationName)).toBe('none');});
for(const outcome of ['success','duplicate','failure'])test(`experiment outcome ${outcome} shows actual spend and return`,async({page})=>{await page.goto('/?qa=1');await page.evaluate(async outcome=>{const q=(window as any).__variantQA;const {experiment,RECIPES}=await import('/src/variant/research.ts' as string);const recipe=RECIPES[0];q.repo.transaction((d:any)=>{d.lessons=['research'];for(const [key,n]of Object.entries(recipe.cost))d.research.reagents[key]=Number(n)*4;for(let i=1;i<100000;i++){d.research.rng=i;const candidate=experiment(d.research,recipe.id);if((outcome==='failure')===(candidate.result===null)){if(outcome==='duplicate'&&candidate.result)d.research.unlocked.push(candidate.result);break;}}});q.go('lab');},outcome);await page.locator('[data-experiment]').click();await page.locator('[data-confirm-experiment]').click();await expect(page.locator('.experiment-outcome')).toHaveClass(new RegExp(outcome));await expect(page.locator('.experiment-outcome')).toContainText('实际投入：');await expect(page.locator('.experiment-outcome')).toContainText('返还：');await page.screenshot({animations:'disabled',path:`.verification/immersive/experiment-${outcome}.png`});});
test('home family selection switches the single primordial specimen',async({page})=>{await page.goto('/?qa=1');for(const [family,name] of [['legume','原豆母体'],['bloom','原花母体'],['root','原根母体'],['fungi','原孢体'],['arthropod','原节肢体']]){await page.locator(`[data-home-family="${family}"]`).click();await expect(page.locator('.primal-resident')).toHaveCount(1);await expect(page.locator('.resident-label')).toContainText(name);await expect(page.locator('.primal-resident .unknown')).toHaveCount(0);}await page.screenshot({animations:'disabled',path:'.verification/immersive/home-primal-arthropod.png'});});
test('primordial family keyboard selection preserves focus and research state',async({page})=>{
 await page.goto('/?qa=1');const before=await page.evaluate(()=>JSON.stringify((window as any).__variantQA.repo.data));
 for(const family of ['bloom','root','fungi','arthropod','legume']){const tab=page.locator(`[data-home-family="${family}"]`);await tab.focus();await page.keyboard.press('Enter');await expect(tab).toBeFocused();await expect(tab).toHaveAttribute('aria-pressed','true');await expect(page.locator('.home-heading h1')).toHaveCount(1);await expect(page.locator('.home-growth .unknown')).toHaveCount(2);}
 expect(await page.evaluate(()=>JSON.stringify((window as any).__variantQA.repo.data))).toBe(before);
 await page.locator('[data-settings]').click();await page.locator('#reduced').check();await page.keyboard.press('Escape');expect(await page.locator('.primal-resident>.organism').evaluate(e=>getComputedStyle(e).animationName)).toBe('none');
});
test('home mobile primary action, discovered growth and research states',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/?qa=1');
 await expect(page.locator('.home-mobile-start')).toHaveText('开始出征');
 for(const state of ['success','duplicate','failure']){await page.evaluate(state=>{const q=(window as any).__variantQA;q.repo.transaction((d:any)=>{if(!d.research.unlocked.includes('V-006'))d.research.unlocked.push('V-006');d.research.history=[{recipe:'test',result:state==='failure'?null:'V-006',duplicate:state==='duplicate'}];});q.render();},state);await expect(page.locator('.home-growth .unknown')).toHaveCount(1);await expect(page.locator('.discovery-count')).toContainText('06');expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(390);}
 await page.reload();await page.locator('.home-mobile-start').click();await expect(page.locator('[data-create-run]')).toBeVisible();await page.locator('[data-create-run]').click();await page.locator('#command [data-nav="hub"]').click();await expect(page.locator('.home-mobile-start')).toHaveText('继续出征');await expect(page.locator('.base-status')).toContainText('回合 1');
});

test('growth opens the selected archive and founder art is consistent across research pages',async({page})=>{
 await page.goto('/?qa=1');await page.locator('[data-home-family="fungi"]').click();const src=await page.locator('.primal-resident img').getAttribute('src');
 await page.locator('[data-home-species="V-004"]').click();await expect(page.locator('#family-filter')).toHaveValue('fungi');await expect(page.locator('#archive-detail .detail-specimen img')).toHaveAttribute('src',src!);await expect(page.locator('[data-node="V-004"]')).toBeFocused();
 await page.locator('[data-home-species]').count();await page.locator('.sidebar [data-nav="lab"]').click();await expect(page.locator('.material-organism img').first()).toHaveAttribute('src','/art/home-legume-v3.png');
});
test('archive filtered edges, relation focus and zoom location remain accessible',async({page})=>{
 await page.goto('/?qa=1');await page.locator('.sidebar [data-nav="archive"]').click();await page.locator('#family-filter').selectOption('legume');
 expect(await page.evaluate(()=>{const ids=new Set([...document.querySelectorAll<HTMLElement>('[data-node]')].map(n=>n.dataset.node));return [...document.querySelectorAll<SVGElement>('[data-parent]')].every(p=>ids.has(p.dataset.parent)&&ids.has(p.dataset.child));})).toBe(true);
 await page.locator('[data-node="V-006"]').focus();await page.keyboard.press('Enter');await expect(page.locator('[data-node="V-006"]')).toBeFocused();await expect(page.locator('.network-lines path.related')).not.toHaveCount(0);
 await page.locator('[data-zoom="+"]').click();await expect(page.locator('[data-zoom="+"]')).toBeFocused();await page.locator('[data-locate]').click();await expect(page.locator('[data-node="V-006"]')).toBeFocused();
 await page.locator('#archive-detail [data-relation="V-001"]').click();await expect(page.locator('[data-node="V-001"]')).toHaveAttribute('aria-pressed','true');
 const first=page.locator('#archive-detail .relations details');if(await first.count())await first.locator('summary').click();
 await page.locator('#archive-detail [data-relation="V-031"]').click();await expect(page.locator('[data-node="V-031"]')).toHaveAttribute('aria-pressed','true');await expect(page.locator('#archive-detail')).toContainText('V-031');
});
test('laboratory probabilities, missing reagents and preview leave research unchanged',async({page})=>{
 await page.goto('/?qa=1');await page.locator('.sidebar [data-nav="lab"]').click();if(await page.locator('[data-skip-lessons]').isVisible())await page.locator('[data-skip-lessons]').click();const before=await page.evaluate(()=>JSON.stringify((window as any).__variantQA.repo.data.research));
 await expect(page.locator('.probability-labels')).toContainText('75.0%');await expect(page.locator('.probability-labels')).toContainText('25.0%');await expect(page.locator('.abnormal-note')).toContainText('包含于成功');await expect(page.locator('.candidate-card').first()).toContainText('未知变种');await expect(page.locator('.candidate-card .unknown')).toHaveCount(1);
 await page.locator('[data-experiment]').click();await page.keyboard.press('Escape');await expect(page.locator('[data-experiment]')).toBeFocused();expect(await page.evaluate(()=>JSON.stringify((window as any).__variantQA.repo.data.research))).toBe(before);
 await page.locator('.sidebar [data-nav="archive"]').click();await page.locator('.sidebar [data-nav="lab"]').click();expect(await page.evaluate(()=>JSON.stringify((window as any).__variantQA.repo.data.research))).toBe(before);
 await page.evaluate(()=>{const q=(window as any).__variantQA;q.repo.transaction((d:any)=>d.research.reagents={});q.render();});await expect(page.locator('[data-experiment]')).toBeDisabled();await expect(page.locator('.cost-row.insufficient')).toContainText('缺少 2');
});

test('original score unlock, scene crossfade, music audition and mute remain independent',async({page})=>{
 await page.goto('/?qa=1');expect(await page.evaluate(()=>(window as any).__variantQA.audio.debug().contextState)).toBe('uninitialized');
 await page.locator('[data-settings]').click();await expect.poll(()=>page.evaluate(()=>(window as any).__variantQA.audio.debug().activeMusic)).toBeGreaterThan(0);
 await page.locator('.audio-audition summary').click();await page.locator('[data-preview-music="laboratory"]').click();await expect.poll(()=>page.evaluate(()=>(window as any).__variantQA.audio.debug().preview)).toBe('laboratory');
 await page.locator('#muted').check();expect(await page.evaluate(()=>(window as any).__variantQA.audio.debug().activeMusic)).toBe(0);await page.locator('#muted').uncheck();await expect.poll(()=>page.evaluate(()=>(window as any).__variantQA.audio.debug().activeMusic)).toBeGreaterThan(0);
 await page.keyboard.press('Escape');expect(await page.evaluate(()=>(window as any).__variantQA.audio.debug().preview)).toBe(null);await page.locator('.sidebar [data-nav="lab"]').click();await expect.poll(()=>page.evaluate(()=>(window as any).__variantQA.audio.debug().scene)).toBe('laboratory');
 for(const v of ['archive','lab','hub','lab'])await page.evaluate(v=>(window as any).__variantQA.go(v),v);
 await page.waitForTimeout(1000);const d=await page.evaluate(()=>(window as any).__variantQA.audio.debug());expect(d.activeMusic).toBe(1);expect(d.failed).toBe(false);
});
test('audio blur freezes score, delayed effects cannot survive pause and reset',async({page})=>{
 await page.goto('/?qa=1');await page.locator('[data-home-family="bloom"]').click();await expect.poll(()=>page.evaluate(()=>(window as any).__variantQA.audio.debug().activeMusic)).toBe(1);
 await page.route('**/shot_spore-1.wav',async route=>{await new Promise(r=>setTimeout(r,600));await route.continue();});
 await page.evaluate(()=>{const q=(window as any).__variantQA;q.audio.play('shot_spore');window.dispatchEvent(new Event('blur'));});
 const before=await page.evaluate(()=>(window as any).__variantQA.audio.debug());expect(before.activeMusic).toBe(0);expect(before.activeSfx).toBe(0);await page.waitForTimeout(900);
 const after=await page.evaluate(()=>(window as any).__variantQA.audio.debug());expect(after.position).toBe(before.position);expect(after.activeSfx).toBe(0);
 await page.locator('[data-home-family="root"]').click();await expect.poll(()=>page.evaluate(()=>(window as any).__variantQA.audio.debug().activeMusic)).toBe(1);
 await page.evaluate(()=>{const q=(window as any).__variantQA;q.audio.play('discovery');q.audio.reset();});await page.waitForTimeout(500);const reset=await page.evaluate(()=>(window as any).__variantQA.audio.debug());expect(reset.activeMusic).toBe(0);expect(reset.activeSfx).toBe(0);expect(reset.position).toBe(0);
});
test('dense layered effects stay below twelve voices and retain warning priority',async({page})=>{
 await page.goto('/?qa=1');await page.locator('[data-home-family="root"]').click();
 await page.evaluate(async()=>{const q=(window as any).__variantQA,{EFFECTS}=await import('/src/variant/audio.ts' as string);for(const d of Object.values(EFFECTS) as any[])await Promise.all(d.urls.map((url:string)=>q.audio.load(url)));q.audio.reset();for(let i=0;i<20;i++)for(const key of Object.keys(EFFECTS).filter(k=>k!=='warning'))q.audio.play(key);q.audio.play('warning');});
 const d=await page.evaluate(()=>(window as any).__variantQA.audio.debug());expect(d.peakSfx).toBe(12);expect(d.activeSfx).toBeLessThanOrEqual(12);expect(d.dropped).toBeGreaterThan(0);expect(d.lastPlayed).toBe('warning');await page.waitForTimeout(3200);expect(await page.evaluate(()=>(window as any).__variantQA.audio.debug().activeSfx)).toBe(0);
});
