import {BY_ID,REAGENTS} from '../content';
import {RECIPES,type Recipe} from '../research';
import type {SaveV4} from '../storage';
import {pageHeading,icon} from './shell';
import {researchArt} from './research-art';
type Context={repo:{data:SaveV4};labMode:string;labRecipe:string;teach:(id:string,text:string)=>void;onRecipe:(id:string)=>void};
export function costText(cost:Record<string,number>){return Object.entries(cost).map(([k,n])=>k==='zero'?`零号试剂 ×${n}`:`${REAGENTS[k.split(':')[0] as keyof typeof REAGENTS]} ${['','Ⅰ','Ⅱ','Ⅲ','Ⅳ'][+k.split(':')[1]]} ×${n}`).join(' + ');}
export function createLabView({repo,labMode,labRecipe,teach,onRecipe}:Context){
 const known=(id:string)=>repo.data.research.unlocked.includes(id);
 function recipeParts(r:Recipe){
  const enough=Object.entries(r.cost).every(([k,n])=>(repo.data.research.reagents[k]??0)>=n),fail=r.results.filter(x=>x.species===null).reduce((n,x)=>n+x.weight,0),success=100-fail,abnormal=r.results.filter(x=>x.species&&['aberrant','zero'].includes(BY_ID[x.species].category)).reduce((n,x)=>n+x.weight,0);
  return {
   parents:`<div class="parent-chamber">${r.parents.map(id=>`<div class="material-organism">${researchArt(BY_ID[id])}<span>${id}</span><b>${BY_ID[id].name}</b><small>永久模板 · 不消耗</small></div>`).join(`<span class="material-join">${icon('lab')}</span>`)}</div>`,
   materials:`<div class="material-slots">${r.parents.map(id=>`<div>${researchArt(BY_ID[id],false,'node')}<span><small>母体模板</small><b>${BY_ID[id].name}</b></span></div>`).join('')}${Object.entries(r.cost).map(([k,n])=>`<div class="reagent-slot">${icon('lab')}<span><small>投入试剂</small><b>${costText({[k]:n})}</b></span></div>`).join('')}</div>`,
   risk:`<div class="risk-summary"><div class="probability-labels"><span>成功 <b>${success.toFixed(1)}%</b></span><span>失败 <b>${fail.toFixed(1)}%</b></span></div><div class="probability-bar" role="img" aria-label="成功 ${success}%，失败 ${fail}%"><span style="width:${success}%"></span><i style="width:${fail}%"></i></div><p class="abnormal-note">${icon('lab')} 异常 ${abnormal.toFixed(1)}% <small>包含于成功</small></p></div>`,
   results:`<div class="candidate-heading"><span>可能形成的结果</span><small>每次实验只产生一个结果</small></div><div class="experiment-results">${r.results.map(x=>`<article class="candidate-card ${x.species?'':'failure-candidate'}"><div class="candidate-visual">${x.species?researchArt(BY_ID[x.species],!known(x.species)):`<span class="failure-symbol">${icon('lab')}</span>`}</div><div><small>${x.species??'未形成稳定物种'}</small><b>${x.species?(known(x.species)?BY_ID[x.species].name:'未知变种'):'实验失败'}</b><strong>${x.weight.toFixed(2)}<em>%</em></strong></div></article>`).join('')}</div>`,
   cost:`<div class="cost-breakdown"><div class="cost-head"><span>试剂</span><span>需要 / 持有</span></div>${Object.entries(r.cost).map(([k,n])=>{const have=repo.data.research.reagents[k]??0;return `<div class="cost-row ${have<n?'insufficient':''}"><span>${costText({[k]:n}).split(' ×')[0]}</span><b>${n} / ${have}</b><small>${have<n?'缺少 '+(n-have):'已备齐'}</small></div>`;}).join('')}</div><div class="experiment-rules"><p>失败仍消耗已确认的试剂。</p><p>重复发现返还每项投入的一半，向下取整。母体模板永久保留。</p></div>`,
   button:`<button class="primary" data-experiment="${r.id}" ${!enough?'disabled':''}>${enough?'预览并确认实验':'试剂不足 · 请前往出征'} ${icon('arrow')}</button>`
  };
 }
 function recipePanel(r:Recipe){const p=recipeParts(r);return `<div class="research-preview">${p.parents}${p.risk}${p.results}${p.cost}${p.button}</div>`;}
 function renderLab(){
  const available=RECIPES.filter(r=>r.kind===labMode&&r.parents.every(known)),r=available.find(r=>r.id===labRecipe)??available[0];onRecipe(r?.id??'');const p=r?recipeParts(r):null;
  document.querySelector('#screen')!.innerHTML=pageHeading('遗传实验室','GENETICS LABORATORY','选择生命的起点，预览一次新的可能。')+`<div class="reagent-inventory"><span class="inventory-label">试剂储备</span>${Object.entries(repo.data.research.reagents).filter(([,n])=>n>0).map(([k,n])=>`<span>${costText({[k]:n})}</span>`).join('')||'<p>暂无试剂，前往出征获取。</p>'}</div><div class="lab-layout"><section class="lab-selection"><h3><small>01</small> 实验条件</h3><div class="archive-tools"><button data-lab-mode="mutation" aria-pressed="${labMode==='mutation'}">单体突变</button><button data-lab-mode="hybrid" aria-pressed="${labMode==='hybrid'}">杂交 / 跨界</button><button data-compatibility>兼容矩阵 ${icon('arrow')}</button></div><label class="recipe-label">选择母体与试剂<select id="recipe-select" ${available.length?'':'disabled'}>${available.map(x=>`<option value="${x.id}" ${r?.id===x.id?'selected':''}>${x.parents.map(id=>BY_ID[id].name).join(' × ')} · ${costText(x.cost)}</option>`).join('')||'<option>暂无可用配方</option>'}</select></label>${p?.materials??'<p>发现兼容模板后，可在这里展开实验。</p>'}</section><section class="lab-stage" aria-label="培养台与候选结果"><h3><small>02</small> 生命培养台</h3>${p?p.parents+p.results:'<p class="lab-empty">目前没有可执行方案，请先发现更多物种。</p>'}</section><section class="lab-summary"><h3><small>03</small> 风险与投入</h3>${p?p.risk+p.cost+`<div class="lab-confirm">${p.button}</div>`:''}<div id="lesson-lab" class="lesson-anchor"></div></section></div><section class="research-log"><span class="eyebrow">EXPERIMENT LOG</span><h2>最近实验</h2><div class="research-log-grid">${repo.data.research.history.slice(0,8).map(h=>{const r=RECIPES.find(r=>r.id===h.recipe),refund=r&&h.duplicate?Object.fromEntries(Object.entries(r.cost).map(([k,n])=>[k,Math.floor(n/2)]).filter(([,n])=>Number(n)>0)):{};return `<article class="log-${h.duplicate?'duplicate':h.result?'success':'failure'}"><span class="outcome-badge">${h.duplicate?'重复发现':h.result?'首次发现':'实验失败'}</span><b>${h.result?BY_ID[h.result].name:'未形成稳定变种'}</b><p>${h.duplicate?'已收录模板保留':h.result?'已永久收录':'母体模板保留'}</p>${r?`<small>实际投入：${costText(r.cost)}</small><small>返还：${Object.keys(refund).length?costText(refund):'无'}</small>`:'<small>该旧记录未包含可查询的配方明细。</small>'}</article>`;}).join('')||'<p class="log-empty">第一份实验报告，等待你的确认。完成实验后，消耗与发现会记录在这里。</p>'}</div></section>`;
  teach('research','选择母体与试剂条件，查看中央候选结果，阅读风险后再确认。新物种会立即永久收录。');
 }
 return {renderLab,recipePanel,costText};
}
