import type {SaveV4} from '../storage';
export type PageName='hub'|'deploy'|'archive'|'lab'|'records';
const paths:Record<string,string>={hub:'M3 11 12 3l9 8M5 10v11h14V10M9 21v-7h6v7',deploy:'m4 20 5-14 11-2-2 11-14 5Zm5-5 6-6',archive:'M4 4h7v16H4zm9 0h7v16h-7M7 8h1m8 0h1',lab:'M9 3h6M10 3v7L4 20h16l-6-10V3M7 15h10',records:'M8 3h8l4 4v14H4V3h4m0 6h8m-8 4h8m-8 4h5',settings:'m12 3 2 3 4-1 1 4 3 3-3 2 1 4-4 1-2 3-3-3-4 1-1-4-3-2 3-3-1-4 4-1 3-3Zm0 6a3 3 0 1 0 0 6 3 3 0 0 0 0-6',menu:'M4 6h16M4 12h16M4 18h16',close:'m6 6 12 12M18 6 6 18',back:'m10 5-7 7 7 7M3 12h18',arrow:'M3 12h18m-7-7 7 7-7 7',leaf:'M20 3C6 3 3 7 5 15c8 4 15-2 15-12ZM4 21 15 9',volume:'M4 9h4l5-4v14l-5-4H4Zm12-1q6 4 0 8',pause:'M8 4v16M16 4v16',play:'m7 4 13 8-13 8Z',refresh:'M20 8a8 8 0 1 0 0 8M20 3v5h-5',lock:'M7 10V7a5 5 0 0 1 10 0v3M5 10h14v11H5Zm7 4v3',bio:'m12 2 8 5v10l-8 5-8-5V7Zm-4 6h5a3 3 0 0 1 0 6H8m0-6v10'};
export function icon(name:string){return `<svg class="ui-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]??paths.leaf}"/></svg>`;}
export const navigation:Array<[PageName,string,string]>=[['hub','研究中枢','RESEARCH HUB'],['deploy','出征部署','EXPEDITION'],['archive','变种档案','SPECIMENS'],['lab','遗传实验室','GENETICS LAB'],['records','人员记录','FIELD RECORDS']];
export function shell(){return `<aside class="sidebar" aria-label="基地导航"><button class="drawer-close" data-dismiss-menu aria-label="关闭菜单">${icon('close')}关闭菜单</button><button class="identity" data-nav="hub"><img src="/favicon.svg?v=variant4" alt="零序列徽记"><span>VARIANT<br><b>ZERO</b><small>零号变种</small></span></button><div class="sidebar-caption">自适应生态署<br><span>培育不可能的生命。</span></div><nav aria-label="主导航">${navigation.map(([id,label,en])=>`<button data-nav="${id}">${icon(id)}<span class="nav-label">${label}<small>${en}</small></span><span class="nav-arrow">${icon('arrow')}</span></button>`).join('')}</nav><button class="settings-link" data-settings>${icon('settings')}<span>设置</span></button><footer><span class="status-dot"></span> 本地研究终端<small>BUILD 0.4 · VARIANT ZERO</small></footer></aside><button class="drawer-scrim" data-dismiss-menu aria-label="关闭菜单" tabindex="-1"></button><header class="terminal-header"><button data-menu aria-expanded="false" aria-controls="base-navigation">${icon('menu')}菜单</button><button data-nav="hub" class="back-home">${icon('back')}研究中枢</button><div class="breadcrumb">自适应生态署 <span>/</span> <b id="page-name">研究中枢</b></div><div class="terminal-state"><span class="status-dot"></span><span>研究档案已连接</span></div></header><main id="screen"></main><main id="deployment" hidden><div id="command"></div><div class="battle-layout"><aside class="trait-rail"><div id="traits"></div><div id="lesson-battle" class="lesson-anchor"></div></aside><section class="arena-column"><div id="battle-strip"></div><div class="arena-wrap"><div id="arena"></div><div id="cells" class="board-cells">${Array.from({length:48},(_,i)=>`<button data-cell="${i}" aria-label="${i<24?'敌方':'己方'} ${Math.floor(i/8)+1} 行 ${i%8+1} 列"></button>`).join('')}</div><div id="battle-status" class="battle-status" hidden></div></div><div id="bench"></div></section><aside class="operations-rail"><div id="unit-info"></div><div id="operations"></div></aside></div><section id="shop"></section></main><div id="lesson" class="lesson" aria-live="polite"></div><div id="modal" hidden></div><div id="toast" role="status"></div>`;}
export function updateShell(view:string,d:SaveV4){document.querySelector('#page-name')!.textContent=navigation.find(x=>x[0]===view)?.[1]??'研究中枢';document.querySelector('.sidebar')!.id='base-navigation';document.querySelectorAll<HTMLElement>('.sidebar [data-nav]').forEach(e=>{e.classList.toggle('active',e.dataset.nav===view);if(e.dataset.nav==='deploy'){const label=e.querySelector('.nav-label')!;label.innerHTML=`${d.active&&d.active.phase!=='ended'?'继续出征':view==='hub'?'开始出征':'出征部署'}<small>EXPEDITION</small>`;e.classList.toggle('primary',view==='hub');}});}
export function pageHeading(title:string,kicker:string,description:string){return `<div class="page-heading"><span class="eyebrow">${kicker}</span><h1>${title}</h1><p>${description}</p></div>`;}
const labels:Record<string,string>={completed:'完成关卡',unlocked:'已解锁关卡',best:'最佳成绩',runs:'出征次数',wins:'胜利次数',bestTime:'最快记录',legacy:'纪念记录',records:'历史成绩',discoveries:'发现记录',version:'旧版版本',phenotypes:'杂交发现',genes:'基因发现',mutations:'突变发现',stages:'阶段成绩'};
export function memorial(value:unknown):string{if(!value||typeof value!=='object')return '<p>暂无旧版纪念记录。新的调查从这里开始。</p>';const entries=Object.entries(value as object);if(!entries.length)return '<p>暂无旧版纪念记录。新的调查从这里开始。</p>';return `<dl class="memorial">${entries.map(([key,v])=>`<div><dt>${labels[key]??'历史条目'}</dt><dd>${Array.isArray(v)?v.length+' 项记录':v&&typeof v==='object'?memorial(v):String(v??'暂无').replace(/[<>&]/g,'')}</dd></div>`).join('')}</dl>`;}
