import {SPECIES,BY_ID,REGIONS,PROTOCOLS,type SpeciesDefinition} from '../content';
import type {SaveV4} from '../storage';
import {createArchiveView} from './archive';
import {createLabView} from './laboratory';
import {pageHeading as header,memorial} from './shell';
type Context={repo:{data:SaveV4};filter:string;archiveMode:string;archiveSelection:string;zoom:number;labMode:string;labRecipe:string;region:number;selectedPool:string[];card:(s:SpeciesDefinition,o?:any)=>string;teach:(id:string,text:string)=>void;onRecipe:(id:string)=>void};
export function createViews(ctx:Context){const {renderArchive,details}=createArchiveView(ctx);const {renderLab,recipePanel,costText}=createLabView(ctx);const {repo,region,selectedPool,card}=ctx;const $=<T extends HTMLElement=HTMLElement>(s:string)=>document.querySelector<T>(s)!;const known=(s:SpeciesDefinition)=>repo.data.research.unlocked.includes(s.id);
function renderPool(){const d=repo.data;$('#screen').innerHTML=header('组建出战基因池','DEPLOYMENT GENOME POOL','选择本局商店可出现的物种。初期携带全部已发现物种；达到 12 种后，选择恰好 12 种。')+`<div class="pool-toolbar"><b>已选 ${selectedPool.length} / ${Math.min(12,d.research.unlocked.length)}</b><div>${[1,2,3,4,5].map(c=>`<span class="${selectedPool.some(id=>BY_ID[id].cost===c)?'available':'missing'}">${c} BIO</span>`).join('')}</div><label>试剂探索倾向 <select id="region">${REGIONS.map((r,i)=>`<option value="${i}" ${i===region?'selected':''} ${i>d.records.unlockedRegion?'disabled':''}>${r.name}${i>d.records.unlockedRegion?' · 未解锁':''}</option>`).join('')}</select></label><button class="primary" data-create-run>进入 20 回合出征</button></div><div class="species-grid pool-grid">${SPECIES.filter(known).map(s=>`<div>${card(s,{select:selectedPool.includes(s.id)})}<button class="pool-toggle" data-pool="${s.id}" aria-pressed="${selectedPool.includes(s.id)}">${selectedPool.includes(s.id)?'移出出战池':'加入出战池'}</button></div>`).join('')}</div>`;}
function renderRecords(){const d=repo.data;$('#screen').innerHTML=header('培育员档案','PERSONNEL RECORD / ADAPTIVE ECOLOGY DIRECTORATE','你的成长是发现新的选择。物种解锁不会提供永久战斗属性。')+`<div class="personnel-banner"><span class="agency-seal">AEA</span><div><span class="eyebrow">ADAPTIVE ECOLOGY DIRECTORATE</span><h2>自适应生态署 · 培育员</h2><p>以发现拓展生态的可能。</p></div></div><div class="record-grid">${[['稳定物种',d.research.unlocked.length],['实验次数',d.research.experiments],['完整出征',d.records.wins],['累计出征',d.records.runs],['最远回合',d.records.bestRound],['最快胜利',d.records.bestTime?Math.round(d.records.bestTime)+' 秒':'等待首次胜利']].map(([k,v])=>`<article><span>${k}</span><b>${v}</b></article>`).join('')}</div><div class="protocol-grid">${PROTOCOLS.map(p=>`<article><h2>${p.title}</h2><p>${p.text}</p></article>`).join('')}</div><h2>区域调查记录</h2><div class="protocol-grid">${REGIONS.map((r,i)=>`<article><span class="eyebrow">ZONE / 0${i+1}</span><h3>${r.name}</h3><p>${d.records.unlockedRegion>=i?r.story:'未解析 · 推进出征以取得该区域的调查记录。'}</p></article>`).join('')}</div><details><summary>旧版纪念档案</summary>${memorial(d.legacy)}</details><p class="local-note">研究数据保存在本机浏览器中。准备阶段自动保存，战斗中刷新将回到本回合开战前。</p><button data-export>导出本地档案</button><button data-help>重看操作手册</button>`;}
return {renderPool,renderArchive,renderLab,renderRecords,details,recipePanel,costText};}
