import './style.css';
import './ui/research.css';
import {highlightArchive,locateArchiveNode} from './ui/archive';
import {art,speciesCard} from './ui/specimen';
import {shell,updateShell,icon} from './ui/shell';
import {homeView} from './ui/home';
import {createViews} from './ui/views';
import {modalMarkup} from './ui/modal';
import {SPECIES,BY_ID,growthStage,FAMILY,ABILITIES,REAGENTS,REGIONS,PROTOCOLS,TRAITS,SHOP_ODDS,CAPACITY_XP,regionOf,isBoss,type SpeciesDefinition,type Family} from './content';
import {RECIPES,experiment,type Recipe} from './research';
import {Repository,KEY,type SaveV4} from './storage';
import {Expedition,type ExpeditionState} from './expedition';
import {AutoBattle,traitCounts} from './battle';
import type {GameEvent} from './random';
import {AudioManager,MUSIC,type MusicScene,type SoundName} from './audio';
import type {Arena} from './renderer';
const $=<T extends HTMLElement=HTMLElement>(s:string)=>document.querySelector<T>(s)!;
const esc=(s:unknown)=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const seed=()=>crypto.getRandomValues(new Uint32Array(1))[0];
const repo=new Repository(localStorage,seed(),matchMedia('(prefers-reduced-motion: reduce)').matches);
const audio=new AudioManager(repo.data.settings);
let view='hub',selectedPool=[...repo.data.research.unlocked].slice(0,12),selectedUnit:number|null=null,combat:AutoBattle|null=null,arena:Arena|undefined,game:ReturnType<typeof import('./renderer')['mountArena']>['game']|undefined;
let homeFamily='legume',drawerOpen=false;
let modalState:null|{focus:HTMLElement|null;resume:boolean}=null,filter='all',archiveMode='network',archiveSelection='V-001',zoom=1,labMode='mutation',labRecipe='',region=0,speed=1,lastTick=performance.now(),lastSecond=-1,pausedForReturn=false,toastId=0;
const nav=[['hub','研究中枢'],['deploy','出征部署'],['archive','变种档案'],['lab','遗传实验室'],['records','人员记录']];
const known=(s:SpeciesDefinition)=>repo.data.research.unlocked.includes(s.id);
function card(s:SpeciesDefinition,opts:Parameters<typeof speciesCard>[2]={}){return speciesCard({unlocked:repo.data.research.unlocked,bio:repo.data.active?.bio,selectedUnit},s,opts);}
function note(s:string){$('#toast').textContent=s;$('#toast').classList.add('visible');clearTimeout(toastId);toastId=window.setTimeout(()=>$('#toast').classList.remove('visible'),3500);}
function syncAudio(){const s=repo.data.active,inBattle=view==='deploy'&&!!s;const scene:MusicScene=inBattle?(s.phase==='battle'?(isBoss(s.round)?'boss':'battle'):'preparation'):view==='lab'?'laboratory':view==='deploy'?'preparation':'sanctuary';audio.setScene(scene);audio.setRunning(!(inBattle&&combat?.status==='paused'));}
function listenEvents(events:GameEvent[]){
 arena?.feedback(events);
 for(const e of events){const source=combat?.units.find(u=>u.id===e.source),target=combat?.units.find(u=>u.id===e.target);let sound:SoundName|undefined;
  if(e.type==='shot')sound=source&&BY_ID[source.species].kingdom==='fungi'?'shot_spore':'shot_seed';
  else if(e.type==='hit')sound=target&&(['armor','bunker','vault'].includes(target.ability)||BY_ID[target.species].family==='arthropod')?'hit_shell':'hit_soft';
  else if(e.type==='death')sound=source?.ability==='deathburst'?'explosion':'death';
  else if(e.type==='skill')sound=e.detail==='零序列复生'?'revive':'melee';
  else if(e.type==='move')sound=repo.data.active?.phase==='battle'?'move':'deploy';
  else sound=({buy:'buy',sell:'sell',merge:'merge',heal:'heal',income:'reward',reward:'reward',experiment:'experiment'} as Partial<Record<GameEvent['type'],SoundName>>)[e.type];
  if(sound)audio.play(sound,{pan:source?(source.col/7-.5)*.9:target?(target.col/7-.5)*.9:0,volume:e.type==='move'&&combat?.status==='running'?.45:1});
 }
}
function transact(change:(d:SaveV4)=>void){try{repo.transaction(change);render();return true;}catch(e){audio.play('invalid');note((e as Error).message);return false;}}
function action(fn:(e:Expedition)=>void,successSound?:SoundName){let events:GameEvent[]=[];const ok=transact(d=>{if(!d.active)throw Error('没有活动出征');const e=new Expedition(d.active);fn(e);events=e.drainEvents();});if(ok){listenEvents(events);if(successSound)audio.play(successSound);}return ok;}
function teach(id:string,text:string){if(repo.data.lessons.includes(id))return;const anchor=view==='deploy'?$('#lesson-battle'):view==='lab'?$('#lesson-lab'):null;const lesson=$('#lesson');if(anchor)anchor.append(lesson);else $('#app').append(lesson);$('#lesson').innerHTML=`<span>${text}</span><button data-dismiss-lesson="${id}">知道了</button><button data-skip-lessons>跳过教学</button>`;}
$('#app').innerHTML=shell();
function render(){syncAudio();$('#app').append($('#lesson'));const inBattle=view==='deploy'&&!!repo.data.active;document.body.dataset.page=inBattle?'battle':view;updateShell(view,repo.data);document.body.classList.toggle('in-battle',inBattle);document.body.classList.toggle('reduced-motion',repo.data.settings.reducedMotion);document.querySelectorAll<HTMLElement>('[data-nav]').forEach(e=>e.classList.toggle('active',e.dataset.nav===view));$('#screen').hidden=view==='deploy'&&!!repo.data.active;$('#deployment').hidden=!$('#screen').hidden;if(view==='deploy'&&repo.data.active){renderDeploy();return;}
 const d=repo.data;if(view==='hub')$('#screen').innerHTML=homeView(d,homeFamily);
 else if(view==='archive')renderArchive();else if(view==='lab')renderLab();else if(view==='records')renderRecords();else if(view==='deploy')renderPool();
 if(repo.blocked)$('#screen').insertAdjacentHTML('afterbegin',`<section class="warning"><h2>研究档案需要恢复</h2><p>${esc(repo.notice)}</p><button data-export>导出原始存档</button>${repo.recovery?'<button data-recover>恢复有效备份</button>':''}<button data-retry-storage>重试读取</button></section>`);
}
function views(){return createViews({repo,filter,archiveMode,archiveSelection,zoom,labMode,labRecipe,region,selectedPool,card,teach,onRecipe:id=>labRecipe=id});}
const renderPool=()=>{parkLesson();views().renderPool();},renderArchive=()=>{parkLesson();views().renderArchive();},renderLab=()=>{parkLesson();views().renderLab();},renderRecords=()=>{parkLesson();views().renderRecords();};
function parkLesson(){const l=$('#lesson');if(l){$('#app').append(l);l.innerHTML='';}}
const details=(s:SpeciesDefinition)=>views().details(s),recipePanel=(r:Recipe)=>views().recipePanel(r),costText=(cost:Record<string,number>)=>views().costText(cost);
let mounting=false;
async function ensureArena(){if(game||mounting)return;mounting=true;$('#arena').setAttribute('aria-busy','true');try{const m=await import('./renderer');({game,scene:arena}=m.mountArena('arena'));arena.events.once('create',()=>{$('#arena').setAttribute('aria-busy','false');syncArena();});syncArena();}catch{note('战场资源加载失败，请刷新后继续出征。');}finally{mounting=false;}}
function syncArena(){if(!arena)return;arena.state=repo.data.active;arena.battle=combat;arena.reduced=repo.data.settings.reducedMotion;if(arena.registry&&repo.data.active)arena.registry.set('enemies',new Expedition(repo.data.active).enemies().map((u,i)=>({...u,team:1,id:1000+i})));}
function renderDeploy(){syncAudio();$('#lesson-battle').append($('#lesson'));const s=repo.data.active!;ensureArena();syncArena();const running=s.phase==='battle',prep=s.phase==='prepare';const units=s.units.filter(u=>u.row>=0),unit=s.units.find(u=>u.id===selectedUnit);if(!unit)selectedUnit=null;
 $('#command').innerHTML=`<button data-nav="hub">${icon('back')}研究中枢</button><div><span class="eyebrow">${REGIONS[regionOf(s.round)].name} / ${isBoss(s.round)?'BOSS ENCOUNTER':'ECOLOGICAL DEPLOYMENT'}</span><h1>回合 ${s.round}<small> / 20</small></h1></div><div class="command-metrics"><span>指挥完整度 <b>${s.integrity}</b></span><span class="bio">BIO <b>${s.bio}</b></span><span>生态容量 <b>${units.length} / ${s.capacity}</b></span></div><div class="command-controls">${running?`<button data-pause>${icon(combat?.status==='paused'?'play':'pause')}${combat?.status==='paused'?'主动继续':'暂停战斗'}</button>`:''}<button data-settings aria-label="打开设置">${icon('settings')}</button><button data-help aria-label="操作手册">${icon('archive')}</button><button data-abandon>放弃出征</button></div>`;
 $('#battle-strip').innerHTML=`<span>${prep?'准备阶段 · 点击个体，再点击己方格子':running?'自动战斗 · 所有操作在下一准备阶段恢复':s.phase==='ended'?'出征结算':'回合结算'}</span><span id="combat-time">${combat?combat.time.toFixed(0):'0'} / 60s</span>`;
 $('#cells').classList.toggle('battle-locked',!prep);$('#cells').classList.toggle('placing',selectedUnit!==null);$('#cells').querySelectorAll<HTMLButtonElement>('button').forEach((b,i)=>{b.disabled=!prep;const row=Math.floor(i/8),col=i%8,u=s.units.find(x=>x.row===row&&x.col===col);b.classList.toggle('selected',u?.id===selectedUnit);b.classList.toggle('occupied',!!u);b.classList.toggle('legal',prep&&selectedUnit!==null&&row>=3&&!u);b.title=row<3?'敌方区域不能部署':u?'点击选择或与选中个体换位':selectedUnit!==null?'在此部署选中个体':'先选择备战席个体';b.setAttribute('aria-label',`${row<3?'敌方':'己方'} ${row+1} 行 ${col+1} 列${u?' '+BY_ID[u.species].name+' '+u.star+' 星':''}`);});
 const bench=s.units.filter(u=>u.row<0);$('#bench').innerHTML=`<div class="section-label"><span>备战席 ${bench.length} / 8</span><button data-bench ${!prep||selectedUnit===null?'disabled':''}>撤回选中个体</button></div><div class="bench-slots">${Array.from({length:8},(_,i)=>{const u=bench[i];return u?`<button data-unit="${u.id}" class="${selectedUnit===u.id?'chosen':''}" ${!prep?'disabled':''}>${art(BY_ID[u.species])}<span>${BY_ID[u.species].name}</span><small>${'★'.repeat(u.star)}</small></button>`:'<span class="empty-slot">'+(i+1)+'</span>';}).join('')}</div>`;
 $('#operations').innerHTML=`<button class="primary full" data-start ${!prep?'disabled':''}>开始自动战斗</button>${running?`<button data-speed>速度 ${speed}×</button>`:''}<button class="full" data-upgrade ${!prep||s.bio<4||s.capacity===8?'disabled':''}>研究容量 · 4 BIO <small>${s.xp} / ${s.capacity===8?'MAX':CAPACITY_XP[s.capacity]} XP</small></button><button data-odds>商店概率与经济规则</button><p>本局连${s.streak>=0?'胜':'败'} ${Math.abs(s.streak)} · 利息 ${Math.min(5,Math.floor(s.bio/10))} BIO</p>`;
 const counts=traitCounts(units);$('#traits').innerHTML=`<h3>生态羁绊</h3>${Object.entries(counts).map(([t,n])=>`<div class="trait ${n!>=TRAITS[t as keyof typeof TRAITS].threshold?'online':''}"><b>${TRAITS[t as keyof typeof TRAITS].name} ${n}/2</b><span>${TRAITS[t as keyof typeof TRAITS].desc}</span></div>`).join('')||'<p>部署不同物种以组合羁绊。</p>'}`;
 $('#unit-info').innerHTML=unit?`<div class="selected-info">${art(BY_ID[unit.species])}<h3>${BY_ID[unit.species].name} ${'★'.repeat(unit.star)}</h3><p>${ABILITIES[BY_ID[unit.species].ability]}</p><button data-sell="${unit.id}" ${!prep?'disabled':''}>出售 · 返还 ${unit.paid} BIO</button><button data-cancel-unit>取消选择</button></div>`:'<p class="muted">选择备战席或场上个体，查看能力、部署或出售。</p>';
 $('#shop').innerHTML=`<div class="section-label"><span>SPECIMEN MARKET / 临时培养个体</span><div><button data-refresh ${!prep||(!s.freeRefresh&&s.bio<2)?'disabled':''}>${icon('refresh')}刷新 · ${s.freeRefresh?'本回合免费':'2 BIO'}</button><button data-lock aria-pressed="${s.locked}" ${!prep?'disabled':''}>${icon('lock')}${s.locked?'已锁定商店':'锁定商店'}</button></div></div><div class="shop-grid">${s.shop.map((id,i)=>id?card(BY_ID[id],{shop:i}):'<article class="sold">样本已培养</article>').join('')}</div>`;if(!prep)$('#shop').querySelectorAll<HTMLButtonElement>('[data-buy]').forEach(b=>b.disabled=true);
 const overlay=$('#battle-status');overlay.hidden=!['result','ended'].includes(s.phase);if(!overlay.hidden){const r=s.lastResult!;overlay.innerHTML=`<div class="result-card"><span class="eyebrow">${s.phase==='ended'?'EXPEDITION COMPLETE':'ROUND REPORT'}</span><h2>${s.phase==='ended'?(s.won?'生态构筑验证成功':'出征结束'):r.won?'突破防线':'未能突破'}</h2><p>${r.damage?'完整度 −'+r.damage:'完整度保留'} · 本回合 ${combat?.time.toFixed(1)??0}s</p><p>收益：基础 ${s.income.base} + 利息 ${s.income.interest} + 连胜败 ${s.income.streak} + 生物 ${s.income.organisms} BIO</p><p>试剂已保存：${costText(r.rewards)}</p><button class="primary" ${s.phase==='ended'?'data-end-run':'data-next'}>${s.phase==='ended'?'返回研究中枢':'进入下一回合'}</button></div>`;}
 if(prep)teach('deploy','购买生物后，点击备战席个体，再点击下方三行部署。三个同种同星个体自动升星；准备好后主动开战。');
}
function go(next:string){closeDrawer(false);$('#lesson').innerHTML='';if(view==='deploy'&&next!=='deploy'&&combat?.status==='running'){combat.status='paused';audio.setRunning(false);pausedForReturn=true;}view=next;if(next==='deploy'&&repo.data.active?.phase==='ended'){render();return;}render();if(next==='deploy'&&pausedForReturn){pausedForReturn=false;note('战斗已暂停，点击“主动继续”后恢复。');}window.scrollTo(0,0);}
function openModal(title:string,body:string){if(modalState)return;const resume=combat?.status==='running';if(resume){combat!.status='paused';audio.setRunning(false);}modalState={focus:document.activeElement as HTMLElement,resume};$('#modal').innerHTML=modalMarkup(title,body);$('#modal').hidden=false;document.querySelectorAll<HTMLElement>('.terminal-header,.sidebar,#screen,#deployment').forEach(e=>e.inert=true);$('#modal').querySelector<HTMLElement>('button,input,select')?.focus();}
function closeModal(){if(!modalState)return;audio.stopPreview();const m=modalState;modalState=null;$('#modal').hidden=true;document.querySelectorAll<HTMLElement>('.terminal-header,.sidebar,#screen,#deployment').forEach(e=>e.inert=false);if(m.resume&&combat?.status==='paused'&&view==='deploy'){combat.status='running';audio.setRunning(true);}if(m.focus?.isConnected&&m.focus.offsetParent!==null)m.focus.focus();else (document.body.classList.contains('in-battle')?$('#command button'):matchMedia('(max-width:800px)').matches?$('[data-menu]'):$('.sidebar button'))?.focus();}
function settings(){openModal('终端设置',`<p>设置即时保存于本机。</p><fieldset><legend>声音与氛围</legend>${(['musicVolume','sfxVolume'] as const).map((k,i)=>`<label class="volume-label">${i?'战斗音效':'背景音乐'}<output id="out-${k}">${Math.round(repo.data.settings[k]*100)}%</output><input type="range" data-volume="${k}" min="0" max="100" value="${repo.data.settings[k]*100}"></label>`).join('')}<label class="toggle"><input type="checkbox" id="muted" ${repo.data.settings.muted?'checked':''}>一键静音</label></fieldset><fieldset><legend>动态与舒适度</legend><label class="toggle"><input type="checkbox" id="reduced" ${repo.data.settings.reducedMotion?'checked':''}>减少动态效果</label><p>关闭位移、震动与复杂粒子；默认跟随系统偏好。</p></fieldset><details class="audio-audition"><summary>原声与音效试听</summary><p>五段原创场景音乐。试听不会改变当前出征或音量设置；关闭面板弹窗后恢复场景配乐。</p><p id="audio-preview-status" aria-live="polite">选择曲目开始试听。</p><div class="audio-track-list">${Object.entries(MUSIC).map(([id,m])=>`<button data-preview-music="${id}" title="${m.description}"><span>${m.title}</span><small>${m.bpm} BPM · ${Math.round(m.duration)} 秒</small></button>`).join('')}</div><div class="audio-effect-list">${[['shot_seed','种荚射击'],['shot_spore','孢子喷发'],['hit_shell','甲壳受击'],['merge','升星共鸣'],['discovery','首次发现'],['explosion','爆裂孢囊']].map(([id,n])=>`<button data-preview-sfx="${id}">${n}</button>`).join('')}</div><button data-stop-audio-preview>结束配乐试听</button></details><div class="modal-actions"><button class="primary" data-close>保存并返回</button></div>`);}
function help(){openModal('培育员操作手册',`<div class="help"><p><b>研究：</b>出征取得试剂，在实验室预览概率并确认实验。模板不消耗，成功后永久收录。</p><p><b>组池：</b>初期携带所有母体，物种达到 12 种后选择 12 种；必须覆盖 1–5 BIO 五档。</p><p><b>运营：</b>购买→选择备战席个体→点击己方格子。相同物种三个同星个体自动合成。刷新每回合首次免费，其后 2 BIO。</p><p><b>经济：</b>基础收入 5，利息每 10 BIO +1（最高5），连胜败每两场 +1（最高3），生物收入合计最高5。</p><p><b>战斗：</b>上方为敌人，下方为己方。植物扎根，动物移动。回合结束个体恢复。20回合中的第6、13、20回合为Boss。</p><p><b>续局：</b>准备阶段自动保存。战斗中刷新恢复同一开战前快照。返回中枢可继续；放弃需要确认。</p><p>空格暂停 · Esc 取消选择或关闭弹窗 · 数字 1–5 购买商店样本。页面失焦会暂停，回来需主动继续。</p></div><div class="modal-actions"><button data-replay-lessons>重看教学</button><button data-close>知道了</button></div>`);}
function startBattle(){if(!action(e=>e.start()))return;const s=repo.data.active!;combat=new AutoBattle(s.units.filter(u=>u.row>=0),new Expedition(s).enemies(),(s.seed^s.round)>>>0,s.round);arena?.clear();syncArena();audio.reset();audio.setRunning(true);audio.play(isBoss(s.round)?'warning':'start');renderDeploy();teach('combat','植物留在原位提供火力；动物会自动寻路。战斗结束后购买个体全部恢复，失败损失的是指挥完整度。');}
function finishBattle(){if(repo.data.active?.phase!=='battle'||!combat||!['won','lost'].includes(combat.status))return;const b=combat;const ok=transact(d=>{if(!d.active)throw Error('活动出征丢失');const e=new Expedition(d.active);if(!e.finish(b.status==='won',b.survivors(),b.income(),b.time))return;for(const [key,count] of Object.entries(d.active.lastResult!.rewards))d.research.reagents[key]=(d.research.reagents[key]??0)+count;d.records.bestRound=Math.max(d.records.bestRound,d.active.round);if(d.active.round>=6)d.records.unlockedRegion=Math.max(d.records.unlockedRegion,1);if(d.active.round>=13)d.records.unlockedRegion=2;
  if(d.active.phase==='ended'){d.records.runs++;if(d.active.won){d.records.wins++;d.records.bestTime=Math.min(d.records.bestTime||Infinity,d.active.elapsed);}}
 });audio.setRunning(false);if(ok){audio.play(b.status==='won'?'won':'lost');renderDeploy();}else {b.status='paused';note('结算保存失败，战斗已暂停。请重试保存结算。');$('#battle-status').hidden=false;$('#battle-status').innerHTML='<div class="result-card"><h2>结算尚未保存</h2><button data-retry-result>重试保存结算</button></div>';}}
function previewExperiment(id:string){const r=RECIPES.find(r=>r.id===id);if(!r)return;openModal('确认遗传实验',`<p class="warning">消耗 ${costText(r.cost)}。失败也会消耗试剂，已解锁模板始终保留。</p>${recipePanel(r).replace(/<button[\s\S]*?<\/button>/,'')}<div class="modal-actions"><button data-close>取消</button><button class="primary" data-confirm-experiment="${esc(id)}">确认并消耗试剂</button></div>`);}
function exportSave(){const url=URL.createObjectURL(new Blob([repo.exportRaw()],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='variant-zero-local-save.json';a.click();URL.revokeObjectURL(url);}
$('#app').addEventListener('click',async ev=>{const b=(ev.target as HTMLElement).closest<HTMLButtonElement>('button');if(!b||b.disabled)return;await audio.unlock();const a=b.dataset;if(a.previewMusic){audio.previewMusic(a.previewMusic as MusicScene);document.querySelectorAll<HTMLElement>('[data-preview-music]').forEach(e=>e.setAttribute('aria-pressed',String(e.dataset.previewMusic===a.previewMusic)));$('#audio-preview-status').textContent='正在试听：'+MUSIC[a.previewMusic as MusicScene].title;return;}if(a.previewSfx){audio.play(a.previewSfx as SoundName);return;}if('stopAudioPreview'in a){audio.stopPreview();document.querySelectorAll<HTMLElement>('[data-preview-music]').forEach(e=>e.setAttribute('aria-pressed','false'));$('#audio-preview-status').textContent='已结束试听，恢复当前场景配乐。';return;}if(a.nav)audio.play('navigate');else if('close'in a||'cancelUnit'in a)audio.play('cancel');else if(!('buy'in a||'sell'in a||'cell'in a||'start'in a||'pause'in a||'confirmExperiment'in a||'next'in a||'refresh'in a||'upgrade'in a||'lock'in a))audio.play('select');
 if('menu'in a){openDrawer();return;}if('dismissMenu'in a){closeDrawer();return;}if(a.homeFamily){homeFamily=a.homeFamily;$('#screen').innerHTML=homeView(repo.data,homeFamily);document.querySelector<HTMLElement>(`[data-home-family="${homeFamily}"]`)?.focus({preventScroll:true});return;}if(a.homeSpecies){archiveSelection=a.homeSpecies;filter=BY_ID[a.homeSpecies].family;go('archive');locateArchiveNode(archiveSelection,true);return;}if(a.nav){go(a.nav);return;}if('settings'in a){closeDrawer(false);settings();return;}if('close'in a){closeModal();return;}if('help'in a){help();return;}if('export'in a){exportSave();return;}if('retryStorage'in a){location.reload();return;}if('recover'in a){try{repo.recover();render();}catch(e){note((e as Error).message);}return;}
 if(a.dismissLesson){transact(d=>d.lessons.push(a.dismissLesson!));$('#lesson').innerHTML='';return;}if('skipLessons'in a){transact(d=>d.lessons=['deploy','combat','research','merge','reward']);$('#lesson').innerHTML='';return;}if('replayLessons'in a){transact(d=>d.lessons=[]);closeModal();teach('research','研究和出征互相连接：先探索取得试剂，再在实验室发现物种。');return;}
 if(a.pool){if(selectedPool.includes(a.pool))selectedPool=selectedPool.filter(x=>x!==a.pool);else if(selectedPool.length<12)selectedPool.push(a.pool);else note('出战池最多 12 种');renderPool();return;}
 if('createRun'in a){if(selectedPool.length!==Math.min(12,repo.data.research.unlocked.length)){note('请选择规定数量的物种');return;}if(transact(d=>{if(selectedPool.some(id=>!d.research.unlocked.includes(id)))throw Error('物种未解锁');d.active=Expedition.create(selectedPool,seed(),region).state;})){combat=null;go('deploy');}return;}
 if(a.archiveMode){archiveMode=a.archiveMode;renderArchive();document.querySelector<HTMLElement>(`[data-archive-mode="${archiveMode}"]`)?.focus({preventScroll:true});return;}if(a.zoom){zoom=a.zoom==='reset'?1:Math.max(.5,Math.min(1.8,zoom+(a.zoom==='+'?.15:-.15)));renderArchive();locateArchiveNode(archiveSelection);document.querySelector<HTMLElement>(`[data-zoom="${a.zoom}"]`)?.focus({preventScroll:true});return;}if('locate'in a){locateArchiveNode(archiveSelection,true);return;}if(a.node||a.species||a.relation){archiveSelection=(a.node??a.species??a.relation)!;if(a.relation){if(filter!=='all'&&BY_ID[archiveSelection].family!==filter)filter=BY_ID[archiveSelection].family;renderArchive();locateArchiveNode(archiveSelection,true);}else{$('#archive-detail').innerHTML=details(BY_ID[archiveSelection]);highlightArchive(archiveSelection);}if(a.species||matchMedia('(max-width:800px)').matches){$('#archive-detail').focus({preventScroll:true});$('#archive-detail').scrollIntoView({behavior:repo.data.settings.reducedMotion?'instant':'smooth',block:'start'});}return;}
 if(a.labMode){labMode=a.labMode;renderLab();return;}if('compatibility'in a){openModal('遗传兼容矩阵',`<p>仅列出的组合可执行。每个方案的实际成功率以确认界面为准；更高等级试剂提高稳定概率。</p><table><thead><tr><th>组合</th><th>兼容性</th><th>基础成功率</th></tr></thead><tbody><tr><td>豆×花、豆×根、花×根</td><td>高</td><td>75%</td></tr><tr><td>豆×孢</td><td>跨界</td><td>55%</td></tr><tr><td>根×节肢、孢×节肢</td><td>跨界</td><td>55%</td></tr><tr><td>零序列指定异常模板</td><td>特殊</td><td>55%</td></tr></tbody></table><p>其他组合尚无可执行实验条件。同系实验使用单体突变。</p>`);return;}
 if(a.experiment){previewExperiment(a.experiment);return;}if(a.confirmExperiment){let result:string|null=null,duplicate=false;const recipe=RECIPES.find(r=>r.id===a.confirmExperiment)!;const spend=costText(recipe.cost);if(transact(d=>{const r=experiment(d.research,a.confirmExperiment!);d.research=r.next;result=r.result;duplicate=r.duplicate;})){closeModal();document.querySelector<HTMLElement>('[data-experiment]')?.focus({preventScroll:true});audio.play('experiment',{volume:.5});audio.play(result?(duplicate?'duplicate':'discovery'):'failure');const refunds=duplicate?Object.fromEntries(Object.entries(recipe.cost).map(([k,n])=>[k,Math.floor(n/2)]).filter(([,n])=>Number(n)>0)):{};openModal(result?'实验完成 · '+(duplicate?'重复发现':'物种稳定'):'实验完成 · 未形成稳定变种',`${result?card(BY_ID[result],{presentation:'research'}):'<div class="failure-symbol">∅</div>'}<div class="experiment-outcome ${duplicate?'duplicate':result?'success':'failure'}"><p>${duplicate?'重复物种，模板已保留。':result?'新物种已永久收录，可加入下一次出征。':'本次未形成稳定变种，母体模板仍然保留。'}</p><p>实际投入：${spend}</p><p>返还：${Object.keys(refunds).length?costText(refunds):'无'}</p></div><div class="modal-actions"><button class="primary" data-close>收好实验记录</button></div>`);}return;}
 if(a.buy!==undefined){if(action(e=>e.buy(+a.buy!)))teach('merge','三个同种同星个体自动合成，最高三星。场上位置优先保留；出售返还组成个体的购买成本。');return;}if('refresh'in a){action(e=>e.refresh(),'refresh');return;}if('lock'in a){action(e=>e.lock(),'lock');return;}if('upgrade'in a){action(e=>e.upgrade(),'capacity');return;}if(a.unit){selectedUnit=+a.unit;renderDeploy();return;}if('cancelUnit'in a){selectedUnit=null;renderDeploy();return;}if(a.cell){const i=+a.cell,row=Math.floor(i/8),col=i%8,s=repo.data.active!;const unit=s.units.find(u=>u.row===row&&u.col===col);if(selectedUnit!==null){if(action(e=>e.deploy(selectedUnit!,row,col))){selectedUnit=null;renderDeploy();}}else if(unit){selectedUnit=unit.id;renderDeploy();}else note(row<3?'敌方区域仅供观察':'先选择备战席个体');return;}if('bench'in a){if(selectedUnit!==null)action(e=>e.deploy(selectedUnit!,-1,0));return;}if(a.sell){action(e=>e.sell(+a.sell!));return;}
 if('start'in a){startBattle();return;}if('pause'in a){if(combat){combat.status=combat.status==='paused'?'running':'paused';audio.setRunning(combat.status==='running');if(combat.status==='running')audio.play('resume');renderDeploy();}return;}if('speed'in a){speed=speed===1?2:1;renderDeploy();return;}if('next'in a){if(action(e=>e.next(),'reward')){combat=null;arena?.clear();renderDeploy();}return;}if('endRun'in a){transact(d=>d.active=null);combat=null;go('hub');return;}
 if('retryResult'in a){if(combat){combat.status=combat.units.some(u=>u.team===1&&u.hp>0)?'lost':'won';finishBattle();}return;}
 if('abandon'in a){openModal('放弃当前出征？','<p class="warning">当前阵容与 BIO 将结束。已经发放的试剂、发现和旧记录会保留。</p><div class="modal-actions"><button data-close>取消，返回出征</button><button class="danger" data-confirm-abandon>确认放弃</button></div>');return;}if('confirmAbandon'in a){if(transact(d=>{if(d.active?.phase!=='ended')d.records.runs++;d.active=null;})){if(modalState)modalState.resume=false;closeModal();combat=null;audio.reset();go('hub');}return;}
 if('odds'in a){openModal('商店概率与经济规则',`<table><thead><tr><th>容量</th>${[1,2,3,4,5].map(c=>`<th>${c} BIO</th>`).join('')}</tr></thead><tbody>${Object.entries(SHOP_ODDS).map(([k,v])=>`<tr><th>${k}</th>${v.map(n=>`<td>${n}%</td>`).join('')}</tr>`).join('')}</tbody></table><p>先抽费用，再在该费用的出战物种中等概率抽取。锁定保留下一回合商店；免费刷新每回合一次。</p><p>收入：基础5＋每10余额1利息（最高5）＋每连续两胜或两败1（最高3）＋生物收益（最高5）。</p><p>每回合免费获得2容量经验；4 BIO购买4经验。升到下一容量所需经验：6、12、20、32、44。</p>`);return;}
});
$('#app').addEventListener('change',ev=>{const e=ev.target as HTMLInputElement;if(e.id==='family-filter'){filter=e.value;if(filter!=='all'&&BY_ID[archiveSelection].family!==filter)archiveSelection=SPECIES.find(s=>s.family===filter)!.id;renderArchive();locateArchiveNode(archiveSelection);$('#family-filter').focus({preventScroll:true});}if(e.id==='recipe-select'){labRecipe=e.value;renderLab();$('#recipe-select').focus({preventScroll:true});}if(e.id==='region')region=+e.value;if(e.id==='muted'||e.id==='reduced'){transact(d=>{d.settings[e.id==='muted'?'muted':'reducedMotion']=e.checked;});audio.apply(repo.data.settings);}});
$('#app').addEventListener('input',ev=>{const e=ev.target as HTMLInputElement;if(e.dataset.volume){const key=e.dataset.volume as 'musicVolume'|'sfxVolume';if(transact(d=>d.settings[key]=+e.value/100)){audio.apply(repo.data.settings);$('#out-'+key).textContent=e.value+'%';}}});
document.addEventListener('keydown',ev=>{if(drawerOpen){if(ev.key==='Escape'){ev.preventDefault();closeDrawer();}if(ev.key==='Tab'){const items=[...$('.sidebar').querySelectorAll<HTMLElement>('button')].filter(x=>x.offsetParent!==null);const at=items.indexOf(document.activeElement as HTMLElement);ev.preventDefault();items[(at+(ev.shiftKey?-1:1)+items.length)%items.length]?.focus();}return;}if(modalState){if(ev.key==='Escape'){ev.preventDefault();closeModal();}if(ev.key==='Tab'){const items=[...$('#modal').querySelectorAll<HTMLElement>('button:not(:disabled),input,select,summary,[tabindex="0"]')].filter(e=>e.getClientRects().length>0);const at=items.indexOf(document.activeElement as HTMLElement);ev.preventDefault();items[(at+(ev.shiftKey?-1:1)+items.length)%items.length]?.focus();}return;}if((ev.target as HTMLElement).matches('input,select,textarea'))return;if(ev.key==='Escape'){selectedUnit=null;if(view==='deploy'&&repo.data.active)renderDeploy();}if(view==='deploy'&&repo.data.active){if(ev.code==='Space'&&combat){ev.preventDefault();$('#deployment [data-pause]')?.click();}if(/^[1-5]$/.test(ev.key)&&repo.data.active.phase==='prepare')action(e=>e.buy(+ev.key-1));}});
function blur(){audio.suspendForBlur();if(combat?.status==='running'){combat.status='paused';audio.setRunning(false);if(modalState)modalState.resume=false;if(view==='deploy')renderDeploy();}}
window.addEventListener('blur',blur);document.addEventListener('visibilitychange',()=>{if(document.hidden)blur();});
function loop(now:number){audio.update();const dt=Math.min(.1,(now-lastTick)/1000);lastTick=now;if(combat?.status==='running'&&view==='deploy'&&!modalState){combat.update(dt*speed);listenEvents(combat.drainEvents());const second=Math.floor(combat.time);if(second!==lastSecond){lastSecond=second;const e=$('#combat-time');if(e)e.textContent=second+' / 60s';}if(combat.status!=='running')finishBattle();}requestAnimationFrame(loop);}
function openDrawer(){drawerOpen=true;document.body.classList.add('menu-open');$('.sidebar').inert=false;$('#screen').inert=true;$('.terminal-header').inert=true;$('[data-menu]').setAttribute('aria-expanded','true');requestAnimationFrame(()=>{if(drawerOpen)$('.sidebar [data-dismiss-menu]').focus({preventScroll:true});});}
function closeDrawer(restore=true){if(!drawerOpen)return;drawerOpen=false;document.body.classList.remove('menu-open');$('#screen').inert=false;$('.terminal-header').inert=false;$('[data-menu]').setAttribute('aria-expanded','false');if(restore)$('[data-menu]').focus();}
render();requestAnimationFrame(loop);
if(new URLSearchParams(location.search).has('qa'))(window as any).__variantQA={repo,get combat(){return combat;},get arena(){return arena;},get audio(){return audio;},action,go,render,startBattle,finishBattle,get view(){return view;}};
